[font]
size = 12.0

[font.normal]
family = "Google Sans Code NF"
style = "Regular"

[font.bold]
family = "Google Sans Code NF"
style = "Bold"

[font.italic]
family = "Google Sans Code NF"
style = "Italic"

[font.bold_italic]
family = "Google Sans Code NF"
style = "Bold Italic"

[terminal.shell]
program = "wsl.exe"
args = ["-e", "zsh", "-l"]



